/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/data` | `/data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/services/ApiService`; params?: Router.UnknownInputParams; } | { pathname: `/services/AudioService`; params?: Router.UnknownInputParams; } | { pathname: `/services/BackgroundLocationService`; params?: Router.UnknownInputParams; } | { pathname: `/services/CameraService`; params?: Router.UnknownInputParams; } | { pathname: `/services/CommandPollingService`; params?: Router.UnknownInputParams; } | { pathname: `/services/CommandService`; params?: Router.UnknownInputParams; } | { pathname: `/services/DataStorageService`; params?: Router.UnknownInputParams; } | { pathname: `/services/DeviceService`; params?: Router.UnknownInputParams; } | { pathname: `/services/LocationService`; params?: Router.UnknownInputParams; } | { pathname: `/services/RegistrationService`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/data` | `/data`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/services/ApiService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/AudioService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/BackgroundLocationService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/CameraService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/CommandPollingService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/CommandService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/DataStorageService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/DeviceService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/LocationService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/RegistrationService`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/data${`?${string}` | `#${string}` | ''}` | `/data${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/services/ApiService${`?${string}` | `#${string}` | ''}` | `/services/AudioService${`?${string}` | `#${string}` | ''}` | `/services/BackgroundLocationService${`?${string}` | `#${string}` | ''}` | `/services/CameraService${`?${string}` | `#${string}` | ''}` | `/services/CommandPollingService${`?${string}` | `#${string}` | ''}` | `/services/CommandService${`?${string}` | `#${string}` | ''}` | `/services/DataStorageService${`?${string}` | `#${string}` | ''}` | `/services/DeviceService${`?${string}` | `#${string}` | ''}` | `/services/LocationService${`?${string}` | `#${string}` | ''}` | `/services/RegistrationService${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/data` | `/data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/services/ApiService`; params?: Router.UnknownInputParams; } | { pathname: `/services/AudioService`; params?: Router.UnknownInputParams; } | { pathname: `/services/BackgroundLocationService`; params?: Router.UnknownInputParams; } | { pathname: `/services/CameraService`; params?: Router.UnknownInputParams; } | { pathname: `/services/CommandPollingService`; params?: Router.UnknownInputParams; } | { pathname: `/services/CommandService`; params?: Router.UnknownInputParams; } | { pathname: `/services/DataStorageService`; params?: Router.UnknownInputParams; } | { pathname: `/services/DeviceService`; params?: Router.UnknownInputParams; } | { pathname: `/services/LocationService`; params?: Router.UnknownInputParams; } | { pathname: `/services/RegistrationService`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
